In [ ]:
#Abitha Sree S

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = np.array([10,20,30,40,50])

In [6]:
print("Array:",arr)

Array: [10 20 30 40 50]


In [11]:
print("Shape of the Array:",arr.shape)

Shape of the Array: (5,)


In [12]:
ab = pd.Series([1,2,3,4,5])

In [13]:
print(ab)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [14]:
array =([10,20,30,40,50,60,70,80,90,100])

In [18]:
print("One Dimensional Array:",array)

One Dimensional Array: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [16]:
mularr= ([[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]])

In [17]:
print("Multi-Dimensional Array:",mularr)

Multi-Dimensional Array: [[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150]]


In [20]:
a =np.zeros((4,5))

In [21]:
b = np.ones((5,4))

In [22]:
print("Zeros:",a)

Zeros: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
print("Ones:",b)

Ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
